[gcp_service_account]
type = "service_account"
project_id = "tonosense"
private_key_id = "11aba885f112ec34643690109ddbd6837394428c"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8T3zlzJoVn9J7\\nSKuk/mzWGF+q8++QvUsjRYzR/vAOB4hN54arycRFdW9fW6t6MKOmHvwlwCQwNzI4\\nH39DLcjZ7T7LU4bbim3TKjLDmUiTrNBGNatSvYqK6unLBo+4T6ZInbrS/nsvjjOz\\noph2sCBx4ZxLmTFAbwjg9eeevs27hUflGPGiLbCZqDP3ubmXgnLvvLNXaNjfJL2y\\nzD2xXFrrT56rWn/q1hGPpMM97q6f2zVbSMryrh9VKtcTahtsuiyn93EX1r7PQIIa\\niDVg7QQ8htRSxUrIb9/V+Yd7EQIuNKKGaPg75IFPyPjmkDf3ntL9RES3QzQ0+D67\\nFtX1LSVZAgMBAAECggEAEEZ9eL4PhjVvQ20DOsornXBzWkrlhni51QVWl7LFTC0d\\n..."
client_email = "tonosense-service-account@tonosense.iam.gserviceaccount.com"
client_id = "104608939051222755475"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tonosense-service-account%40tonosense.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
